#!/usr/bin/expect -f
set timeout 2
set passphrase [lindex $argv 0]

spawn reprepro -b {*}[lrange $argv 1 end]
expect {
        "*passphrase:*" {
                send -- "$passphrase\r"
        }
}
expect {
        "*passphrase:*" {
                send -- "$passphrase\r"
        }
}
interact
